# Generated by Django 5.2.7 on 2025-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wants_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
