# Generated by Django 5.2.7 on 2025-10-22 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_customuser_wants_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribed_journalists',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_authors',
            field=models.ManyToManyField(blank=True, related_name='author_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.publisher'),
        ),
    ]
