# Generated by Django 5.2.7 on 2025-10-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_customuser_subscribed_journalists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
