# Generated by Django 5.2.7 on 2025-10-31 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsletter_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Publisher', 'Publisher'), ('Editor', 'Editor'), ('Journalist', 'Journalist')], max_length=15),
        ),
    ]
